config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  post '/mortgage/calculate',    to: 'mortgage#calculate'
  get '/mortgage',    to: 'mortgage#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/mortgage_controller.rb
class MortgageController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def calculate
    #Inputs
    loan = params[:loan_amount].to_f
    rate = params[:interest_rate].to_f
    term = params[:term].to_f
    if params[:term_unit].to_i == 2
      term = term * 12
    end


    #Calculations
    r = (rate/12)/100

    top_half = ((1+r)**term)*r*loan
    bottom_half = ((1+r)**term)-1
    repayment = top_half/bottom_half

    interest = (repayment*term) - loan


    #Array testing
    @amount_owed = []
    @amount_paid = []
    for i in 0..term
      @amount_owed << (((1+r)**i)*loan) - (((((1+r)**i) - 1)/((1+r)-1))*repayment)
      @amount_paid << (((((1+r)**i) - 1)/((1+r)-1))*repayment)
    end



    #Outputs
    if params[:term_unit].to_i == 2
      @term_length = (term/12).to_i.to_s + " years"
    else
      @term_length = (term).to_i.to_s + " months"
    end
    @monthly_repayment = "%5.2f" % repayment
    @interest_paid = "%5.2f" % interest
    @loan_amount = "%5.0f" % loan
    @interest_rate = rate
    @term_length_in_months = term

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/salesforce'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Connected Mortgage" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Connected Mortgage" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/mortgage/calculate.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-4">
			Borrowed Amount = <%= number_to_currency(@loan_amount)  %> ($<%= number_to_human(@loan_amount) %>) <br>
			Term Length = <%= @term_length %><br>
			Interest Rate = <%= @interest_rate %>%<br>

			Monthly repayment = <%= number_to_currency(@monthly_repayment) %><br>

			Total Interest Payable = <%= number_to_currency(@interest_paid) %> ($<%= number_to_human(@interest_paid) %>) <br>
		</div>
		<div class="col-md-4">
			<img src="<%=Gchart.pie(:data => [300, 400], :labels =>['principal', 'interest'], :bg => 'eeeeee') %>"/>
		</div>
	</div>
	<div class="row">
		<br>
		<div class="col-md-4">
			<table>
				<tr><th>Month: </th><th>Amount owed each month: </th><th>Aggregate paid each month: </th></tr>
					<% for i in 0..@term_length_in_months - 1 %>
					<tr><td><%= i %></td><td><%= number_to_currency(@amount_owed[i]) %></td><td><%= number_to_currency(@amount_paid[i]) %></td></tr>
				<% end %>
			</table>
		</div>
		<div class="col-md-4">
			<img src="<%=Gchart.line(:data => [@amount_paid, @amount_owed], :legend =>['amount paid', 'amount owed'] , :theme => :thirty7signals, :bg => 'eeeeee' )%>"/>
		</div>
	</div>
</div>

app/views/mortgage/index.html.erb
<div class="container">
  <div class="row">
    <h3>Mortgage</h3>
    <div class="column">
      <div class="row">
        <div class="span6 offset3">
          <%= form_tag('/mortgage/calculate') do |f| %>
          <div class="form-group">
            <%= label_tag(:loan_amount, "Total Loan Amount") %>
            <%= text_field_tag(:loan_amount, nil, :placeholder => 'in $') %>
            </div>
            <div class="form-group">
            <%= label_tag(:interest_rate, "Interest Rate") %>
            <%= text_field_tag(:interest_rate, nil, :placeholder => 'e.g. 10.4') %>%
            </div>
            <div class="form-group">
            <%= label_tag(:term, "Length of mortgage") %>
            <%= text_field_tag(:term) %> 
            <%= select_tag :term_unit, "<option value=1 selected='selected'>Months</option><option value=2>Years</option>".html_safe %>
            <br><br>
            <%= submit_tag 'Submit', :class => 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

<p><%= link_to 'Mortgage Calculator', mortgage_path %> </p>